#список требований
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - На странице товара и в каталоге нужно выводить название, рейтинг, цена со скидкой и без нее
  - Пользователь должен иметь возможность добавлять товар в корзину и продолжать выбирать товары в каталоге
  - На странице корзины пользователь должен иметь возможность удалить товар из корзины
  - На странице корзины пользователь должен иметь возможность продолжить выбирать товары в каталоге
  - На странице корзины пользователь должен иметь возможность оформить заказ с переходом на страницу оплаты
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен иметь мобильную версию
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Корзина будет храниться в сессии браузера
  - Сайт должен быть SPA-приложением
implicit:
  - Необходимо сделать форму регистрации с уточнением личных данных пользователя
    # это нужно для того, чтобы в дальнейшем при оформлении заказа была связь с пользователем для отправки заказа; а так же доступность пользователю просмотра интернет-магазина, списка заказов, корзины с разных устройств.
  - Cайт должен иметь языковую адаптивность
  - Шапка сайта с названием, кнопками "язык", "корзина" и "магазин" должна быть статична и оставаться видимой при скролле
